services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "${WEB_SERVER_PORT}:80"
      - "${WEB_SERVER_SSL_PORT}:443"
    volumes:
      - ./src:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=bnovo-api
    volumes:
      - ./src/database/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local